name: Build & publish mitmproxy

on:
  push:
    tags:
      - 'mitmproxy_v*'
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Extract version from tag
        id: extract_version
        run: |
          VERSION=${GITHUB_REF#refs/tags/mitmproxy_v}
          echo "VERSION_TAG=$VERSION" >> $GITHUB_ENV
          echo "Extracted version: $VERSION"

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./mitmproxy_dockerfile/
          file: ./mitmproxy_dockerfile/Dockerfile
          push: true
          platforms: linux/amd64,linux/arm64
          tags: |
            paul2tertianet/tn:mitmproxy_wise_automation_${{ env.VERSION_TAG }}
            paul2tertianet/tn:mitmproxy_wise_automation_latest
          cache-from: type=registry,ref=paul2tertianet/tn:mitmproxy_wise_automation_latest
          cache-to: type=inline
